### ISSUE TITLE
Re  In VR gyroscope camera tracking is Disabled

### ISSUE THREAD

**Issue by quantumalchemy** [zach-capalbo/vartiste#13]
Hi  In VR mode / in Android / chrome
gyroscope  is disabled when vartiste is used.

Anyway to enable this in vr for mobile devices?
I want to develop for vr  / mobile (cardboard vr) 
has normal gyro in vr  to move around 
** Then  toggle off gyro (in look-controls?)  and  activate  a-cursor / gaze / fusing for  drawing
when painting on the canvas
Do you thing this functionality is possible with your  aframe component?
Thanks

**Comment by zach-capalbo** [comment]
Hi!

I've tested https://codepen.io/zach-capalbo/pen/oNbKagV and https://vartiste.xyz on my Android/Chrome device, and the gyro seems to work, even in VR (cardboard/daydream) mode.

Are you using the [`vartiste-user-root`](https://vartiste.xyz/docs.html#vartiste-user-root) component, or are you setting up your own camera rig?

If you have a demo or example code that demonstrate the issue, it could be helpful for figuring out what's going on.

Thanks

**Comment by quantumalchemy** [comment]
Hi
the component  --> aframe-environment-component:
https://github.com/supermedium/aframe-environment-component
<a-entity environment="preset:osiris"></a-entity>
Line was left in  from a previous project .. although the script was not included in head
aframe  locked up when in VR  .. strange  
took it out and now OK
Thanks!
